import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '../scss/main.scss'
import { AuthProvider } from '@/context/Auth.Context';
import { NextRouter } from 'next/router';

interface RootLayoutProps {
  children: React.ReactNode;
  router: NextRouter;
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Masso Jonas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, router
}: RootLayoutProps) {
  return (
    <html lang="en">
      <AuthProvider router={router}>
        <body className={inter.className}>{children}</body>
      </AuthProvider>
    </html>
  )
}
